#importing modules
import argparse
import sys
import os
import time

# our  functions
def registration(user_name, password):
    if user_name == "":
        user_name = "Larry"
    if password == "":
        password = "GraT%DsT"
    tel_number = "+49 154 155 11 11"
    reg_success = True # can be False if something went wrong

    return user_name, password, tel_number, reg_success

def login(user_name, password):
    if user_name == "": 
        user_name = "Larry"
    log_success = True # can be False if something went wrong
    return user_name, log_success
    
def add_purchase(purchases):
    print("ADDING PURCHASE\n"*5)
    

def report(purchases):
    print("GENERATING REPORT\n"*10)

# clearing screen

os.system("clear")

# parsing arguments from Command Line

parser = argparse.ArgumentParser(
    description="This program allows you to track your Amazon expenses"
)

parser.add_argument(
    "user_name",
    nargs="?",
    type=str,
    default="",
    help="User name for registration (optional)"
)
parser.add_argument(
    "password",
    nargs="?",
    type=str,
    default="",
    help="Password for registration (optional)"
)

args = parser.parse_args()

user_name = args.user_name
password = args.password


# passing the user_name and password to registration 

registred_user = registration(user_name, password)

# print(registred_user)

# expecting return from function registration -> user_name, password, success

if registred_user[-1]: # checking if registration is successful
    user_name = registred_user[0] # updating user name
    password = registred_user[1] # updating password
    
else:
    print()
    print("Sorry... Something went wrong with the registration. Please try again")
    print()
    sys.exit(1)
    

# passing user name and password to compare with user input
logged = login(user_name, password)


# checking if login was successful, last returned argument - success
if logged[-1]: 
    user_name = logged[0]
    if user_name in registred_user:  # this part is mostly for fututre to build multi-user environmnt
        tel_number = registred_user[2]
    else: 
        print("Sorry. No such user in our database") 
        sys.exit(1)
    
else: 
    print()
    print("Sorry... Something went wrong with the logging in. Please try again")
    print()
    sys.exit(1)
    
print(f"Hello, {user_name}! Welcome to the Amazon Expense Tracker!")
menu_message = """What would you like to do?
1. Enter a purchase
2. Generate a report
3. Quit"""

# generation empty dictionary for dictionaries generated by add_purchase()
purchases = dict()  

while True: 

    print(menu_message)
    user_choice = input("Enter your choice (1/2/3): ")

    match user_choice: 
        case "1":
            add_purchase(purchases)
        case "2": 
            report(purchases)
        case "3": 
            break
        case other:
            print("Sorry. Operation entered is not valid. Please select from the available options")
            continue
        

# quitting

print("Saving your data", end=".")

#printing dots 
for _ in range(10):
    time.sleep(0.2)
    print(".", end="", flush=True)
    
print()

print("Quitting program", end=".")

#printing dots 
for i in range(10):
    print(".", end="", flush=True)
    time.sleep(0.5)       

print()
    
